{{ if .Values.cloudflareSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
data:
  api-key: {{ .Values.cloudflareSecret.apiKey | b64enc }}
{{ end }}
