{{ if .Values.grafanaSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafanacred
  namespace: default
type: Opaque
data:
  admin-user: {{ .Values.grafanaSecret.user | b64enc }}
  admin-password: {{ .Values.grafanaSecret.password | b64enc }}
{{ end }}
