{{ if .Values.createConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polkadot-deployer.custom-chainspec-configmap" . }}
  namespace: {{ .Values.namespace }}
data:
  custom_chainspec.json: |-
    {{- $totalItems := len .Values.chainspec.keys.stash }}
    {{- $lastIndex := sub $totalItems 1 }}
    {
      "name": {{ .Values.deploymentName | quote }},
      "id": {{ .Values.deploymentName | quote }},
      "bootNodes": [
        {{- $lastBootIndex := sub (len .Values.bootNodes) 1}}
        {{- range $index, $value := .Values.bootNodes }}
        {{ $value | quote }}{{- if ne $index $lastBootIndex }},{{- end }}
        {{- end }}
      ],
      "protocolId": "dot",
      "properties": {
        "tokenDecimals": 15
      },
      "genesis": {
        "runtime": {
          "aura": {
            "authorities": [
              {{- range $index, $value := .Values.chainspec.keys.session }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "indices": {
            "ids": [
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "balances": {
            "balances": [
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              [
                {{ $value | quote }},
                1048576000000000000
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "session": {
            "keys": [
              {{- $sessionKeys := .Values.chainspec.keys.session }}
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              [
                {{ $value | quote }},
                {
                  "ed25519": {{ index $sessionKeys $index | quote }}
                }
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "staking": {
            "validatorCount": {{ $totalItems }},
            "invulnerables": [
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ],
            "stakers": [
              {{- $controllers := .Values.chainspec.keys.controller }}
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              [
                {{ $value | quote }},
                {{ index $controllers $index | quote }},
                5000,
                "Validator"
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "grandpa": {
            "authorities": [
              {{- range $index, $value := .Values.chainspec.keys.session }}
              [
                {{ $value | quote }},
                1
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "sudo": {
            "key": "{{ index .Values.chainspec.keys.controller 0 }}"
          }
        }
      }
    }
{{ end }}
