{{ if .Values.vpn.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polkadot-deployer.vpnCommonName" . }}
  namespace: {{ .Values.namespace }}
data:
  default.net: |-
    peers:
    {{- range $index, $value := .Values.vpn.peers }}
    - {{ $value }}
    {{- end }}
    shared_key: {{ .Values.vpn.secret | quote }}
    ifup: "ifconfig $IFNAME {{ .Values.vpn.cidr }} mtu 1400"
    crypto: aes256
    device_name: vpncloud0
{{ end }}
