{{- if not .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-chainspec-{{ .Release.Name }}
  labels:
    type: local
spec:
  storageClassName: local-chainspec
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/chainspec"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-data-{{ .Release.Name }}
  labels:
    type: local
spec:
  storageClassName: local-data-{{ .Release.Name }}
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-{{ .Release.Name }}"
{{- end }}
