apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "polkadot-deployer.sessionInjectionName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "polkadot-deployer.sessionInjectionName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "polkadot-deployer.sessionInjectionName" . }}
  namespace: {{ .Values.nmespace }}
