{{ if .Values.externalAccess -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: {{ .Values.namespace }}
data:
  api-key: {{ .Values.cloudflareApiKey | b64enc }}
{{ end }}
