apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polkadot-deployer.sessionKey" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  grandpa-session-key: {{ .Values.keys.session_grandpa | b64enc }}
  babe-session-key: {{ .Values.keys.session_babe | b64enc }}
  parachain-validator-session-key: {{ .Values.keys.session_parachain_validator | b64enc }}
  imonline-session-key: {{ .Values.keys.session_imonline | b64enc }}
