{{ if .Values.nodeKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polkadot-deployer.nodeKey" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  node-key: {{ .Values.nodeKey | b64enc }}
{{ end }}
