apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 30333
    name: p2p
  - port: 9933
    name: http-rpc
  - port: 9944
    name: websocket-rpc
  selector:
    app: {{ .Release.Name }}
