{{ if .Values.createBootnodeService -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.bootnodeService" . }}
  namespace: {{ .Values.namespace }}
  labels:
    node: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.p2pPort }}
    name: p2p
  selector:
    node: {{ .Release.Name }}
{{ end }}
