{{ if .Values.externalAccess }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: 80
    targetPort: websocket-rpc
  selector:
    app: {{ .Chart.Name }}
{{ end -}}
