apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.rpcService" . }}
  namespace: {{ .Values.namespace }}
  labels:
    node: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.rpcPort }}
    name: http-rpc
  selector:
    node: {{ .Release.Name }}
