apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.p2pService" . }}
  namespace: {{ .Values.namespace }}
  labels:
    node: {{ .Release.Name }}
spec:
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.p2pPort }}
    name: p2p
    nodePort: {{ .Values.p2pPort }}
  selector:
    node: {{ .Release.Name }}
  type: NodePort
