apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccount: {{ include "polkadot-deployer.serviceAccount" . }}
      {{- if .Values.chainspec.custom }}
      initContainers:
      - name: {{ .Release.Name }}-init
        image: {{ .Values.initImage.repo }}:{{ .Values.initImage.tag }}
        command:
        - /app/merge_chainspec.sh
        - /app/custom_chainspec.json
        - {{ .Values.chainspec.path }}
        volumeMounts:
        - name: chainspec
          mountPath: /chainspec
        - name: custom-chainspec
          mountPath: /app/custom_chainspec.json
          subPath: custom_chainspec.json
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - --chain={{ .Values.chainspec.path }}
        - --name={{ .Values.name }}
        - -d=/data
        - --rpc-external
        - --ws-external
        - --key={{ .Values.key }}
        {{- if .Values.validator }}
        - --validator
        {{- end }}
        {{- if .Values.mainNode }}
        - --node-key={{ .Values.nodeKey }}
        {{- else }}
        - --bootnodes={{ include "polkadot-deployer.bootnodes" . }}
        {{- end }}
        ports:
        - containerPort: 30333
          name: p2p
        - containerPort: 9933
          name: http-rpc
        - containerPort: 9944
          name: websocket-rpc
        readinessProbe:
          httpGet:
            path: /health
            port: http-rpc
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http-rpc
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
        - name: chainspec
          mountPath: /chainspec
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        resources:
{{- toYaml .Values.resources | indent 10 }}
      volumes:
      - name: custom-chainspec
        configMap:
          name: {{ include "polkadot-deployer.custom-chainspec-configmap" . }}
      {{- if not .Values.persistence.enabled }}
      - name: data
        emptyDir: {}
      - name: chainspec
        emptyDir: {}
      {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.dataSize }}
  - metadata:
      name: chainspec
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.chainspecSize }}
      {{ end }}
