apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    node: {{ .Release.Name }}
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      node: {{ .Release.Name }}
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        node: {{ .Release.Name }}
        app: {{ .Chart.Name }}
    spec:
      serviceAccount: {{ include "polkadot-deployer.serviceAccount" . }}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true
      {{- if .Values.dnsNameservers }}
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
{{ toYaml .Values.dnsNameservers | indent 8 }}
      {{ end }}
      {{- if not .Values.chainspec.preset }}
      initContainers:
      - name: {{ .Release.Name }}-init
        image: {{ .Values.initImage.repo }}:{{ .Values.initImage.tag }}
        command:
        {{- if .Values.chainspec.custom }}
        - /app/merge_chainspec.sh
        - /app/custom_chainspec.json
        {{- else }}
        - cp
        - /app/{{ .Values.chainspec.name }}
        {{- end }}
        - {{ include "polkadot-deployer.chainspecName" . }}
        volumeMounts:
        - name: chainspec
          mountPath: {{ .Values.chainspec.basePath }}
        {{- if .Values.chainspec.custom }}
        - name: custom-chainspec
          mountPath: /app/custom_chainspec.json
          subPath: custom_chainspec.json
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
        - -c
        - exec /usr/local/bin/polkadot
          --chain={{ include "polkadot-deployer.chainspecName" . }}
          --name={{ .Values.name }}
          -d=/data
          --rpc-external
          --rpc-cors all
          --ws-external
          --port {{ .Values.p2pPort }}
          --node-key=$(cat /etc/polkadot/node-key)
        {{- if .Values.validator }}
          --validator
        {{- end }}
        {{- if .Values.telemetry }}
          --telemetry-url {{ .Values.telemetry }}
        {{- end }}
        {{- if .Values.extraArgs }}
        {{ .Values.extraArgs }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.p2pPort }}
          name: p2p
        - containerPort: {{ .Values.rpcPort }}
          name: http-rpc
        - containerPort: 9944
          name: websocket-rpc
        readinessProbe:
          httpGet:
            path: /health
            port: http-rpc
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http-rpc
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
        {{- if not .Values.chainspec.preset }}
        - name: chainspec
          mountPath: {{ .Values.chainspec.basePath }}
        {{- end }}
        - name: node-key
          mountPath: /etc/polkadot/node-key
          subPath: node-key
        securityContext:
          allowPrivilegeEscalation: false
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: node-key
        secret:
          secretName: {{ include "polkadot-deployer.nodeKey" . }}
          defaultMode: 256
          items:
          - key: node-key
            path: node-key
      {{- if .Values.chainspec.custom }}
      - name: custom-chainspec
        configMap:
          name: {{ include "polkadot-deployer.custom-chainspec-configmap" . }}
      {{- end }}
      {{- if not .Values.persistence.enabled }}
      - name: data
        hostPath:
          path: /{{ .Release.Name}}-data
      - name: chainspec
        hostPath:
          path: /{{ .Release.Name}}-chainspec
      {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      resources:
        requests:
          storage: {{ .Values.persistence.dataSize }}
  - metadata:
      name: chainspec
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      resources:
        requests:
          storage: {{ .Values.persistence.chainspecSize }}
      {{ end }}
