version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/polkadot-deployer .

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - run:
          name: Import external alertrules
          command: |
            scripts/alertrules/import.sh
      - run:
          command: |
            /scripts/publish-chart.sh

  importAndTestPrometheusRules:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - run:
          name: Install missing dependencies
          command: |
            YQ_VER=3.3.2
            wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VER}/yq_linux_amd64
            chmod +x /usr/local/bin/yq

            PROM_VER=2.18.1
            wget -O /tmp/prometheus.tgz https://github.com/prometheus/prometheus/releases/download/v${PROM_VER}/prometheus-${PROM_VER}.linux-amd64.tar.gz
            tar -xvf /tmp/prometheus.tgz prometheus-${PROM_VER}.linux-amd64/promtool -C /tmp
            mv /tmp/prometheus-$PROM_VER.linux-amd64/promtool /usr/local/bin/
      - run:
          name: Import external alertrules
          command: |
            scripts/alertrules/import.sh
      - run:
          command: |
            scripts/test_prometheus_rules.sh


workflows:
  version: 2
  test-deploy:
    jobs:
      - buildImage:
          filters:
            tags:
              only: /.*/
      - importAndTestPrometheusRules:
          filters:
            tags:
              only: /.*/
      - publishChart:
          requires:
            - buildImage
            - importAndTestPrometheusRules
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
