{{ if and (not .Values.local) (not .Values.benchmark) -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "polkadot-deployer.certificateName" . }}
spec:
  secretName: {{ include "polkadot-deployer.tlsSecretName" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ include "polkadot-deployer.websocketsDomain" . }}
{{ end }}
---
{{- if .Values.monitoring }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-tls
  namespace: {{ .Values.grafana.namespace }}
spec:
  secretName: {{ include "polkadot-deployer.grafanaTlsSecretName" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ include "polkadot-deployer.grafanaDomain" . }}
{{ end }}
