{{ if and (not .Values.local) (not .Values.benchmark) -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "polkadot-deployer.certificateName" . }}
spec:
  secretName: {{ include "polkadot-deployer.tlsSecretName" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ include "polkadot-deployer.websocketsDomain" . }}
  {{- if .Values.monitoring }}
  - {{ include "polkadot-deployer.grafanaDomain" . }}
  {{- end }}
{{ end }}
