{{ if .Values.monitoring -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Values.grafana.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    {{- if .Values.grafana.whitelistSourceRange }}
    ingress.kubernetes.io/whitelist-source-range: {{ .Values.grafana.whitelistSourceRange }}
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location /metrics {
        deny all;
      }
spec:
  tls:
  - hosts:
      - {{ include "polkadot-deployer.grafanaDomain" . }}
    secretName: {{ include "polkadot-deployer.grafanaTlsSecretName" . }}
  rules:
  - host: {{ include "polkadot-deployer.grafanaDomain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
{{ end }}
