{{ if and (not .Values.local) (not .Values.benchmark) -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@web3.foundation

    privateKeySecretRef:
      name: letsencrypt

    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflareEmail }}
          apiKeySecretRef:
            name: cloudflare-credentials
            key: api-key
{{ end }}
