apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector: {}
  ingress:
  - ports:
    - protocol: tcp
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
