{{ if not .Values.local -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.p2pService" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "polkadot-deployer.p2pDomain" . }}.
spec:
  ports:
  - port: 30333
    name: p2p
  selector:
    node: polkadot-node-0
  type: LoadBalancer
{{ end }}
