{{ if and (not .Values.local) (not .Values.benchmark) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.websocketService" . }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  ports:
  - name: websocket-rpc
    port: 9944
  selector:
    node: polkadot-node-0
{{ end }}
