{{ if not .Values.local -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.websocketService" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: websocket-rpc
    port: 9944
  selector:
    node: polkadot-node-0
{{ end }}
