image:
  repo: parity/substrate
  tag: 2.0.0-79dd9c830

initImage:
  repo: web3f/polkadot-deployer
  tag: f1cd64f0838646f1c295c7973ca1b9089df31be7

name: testnet-0
deploymentName: testnet

namespace: default

chainspec:
  custom: true
  basePath: "/chainspec"
  file: "chainspec.json"
  keys:
    session: ["session_key_1", "session_key2"]
    stash: ["stash_key_1", "stash_key2"]
    controller: ["controller_key_1", "controller_key2"]

key: "session_key"
nodeKey: "0000000000000000000000000000000000000000000000000000000000000001"

bootNodes:
- "/dns4/polkadot-node-0/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR"

createBootnodeService: false
createConfigMap: false

validator: false

resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"

persistence:
  enabled: false
  dataSize: 32Gi
  chainspecSize: 10Mi
  storageClassName: standard
  accessModes: [ "ReadWriteOnce" ]

dnsNameservers:
- 173.245.58.93
- 173.245.59.247

telemetry: ""

p2pPort: 30333
