image:
  repo: web3f/polkadot
  tag: kusama

initImage:
  repo: web3f/polkadot-deployer
  tag: 5ee15f0d615952c217114bac4612cd5616e0cbb4

name: testnet-0
deploymentName: testnet

namespace: default

chainspec:
  preset: false
  custom: true
  basePath: "/chainspec"
  name: "chainspec.json"
  addresses:
    session: ["session_key_1", "session_key2"]
    stash: ["stash_key_1", "stash_key2"]
    controller: ["controller_key_1", "controller_key2"]

keys:
  session_grandpa: "session_key"
  session_babe: "session_key"
  session_imonline: "session_key"

nodeKey: "0000000000000000000000000000000000000000000000000000000000000001"

bootNodes:
- "/dns4/polkadot-node-0/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR"

createBootnodeService: false
createConfigMap: false

validator: true

resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"

persistence:
  enabled: false
  dataSize: 128Gi
  chainspecSize: 1Gi
  accessModes: [ "ReadWriteOnce" ]

dnsNameservers:
- 173.245.58.93
- 173.245.59.247

telemetry: ""

p2pPort: 30333
rpcPort: 9933

extraArgs: ""
