image:
  repo: web3f/polkadot
  tag: kusama-v0.7.16

initImage:
  repo: web3f/polkadot-deployer
  tag: 061894c29a2b44ce049e5247692c91dcae8e89e6

name: testnet-0
deploymentName: testnet

namespace: default

chainspec:
  preset: false
  custom: true
  basePath: "/chainspec"
  name: "chainspec.json"
  addresses:
    session: ["session_key_1", "session_key2"]
    stash: ["stash_key_1", "stash_key2"]
    controller: ["controller_key_1", "controller_key2"]

keys:
  session_grandpa: "session_key"
  session_babe: "session_key"
  session_imonline: "session_key"
  session_parachain: "session_key"

bootNodes:
- "/dns4/polkadot-node-0/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR"

createBootnodeService: false
createConfigMap: false

validator: true

resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"

persistence:
  enabled: false
  dataSize: 128Gi
  chainspecSize: 1Gi
  accessModes: [ "ReadWriteOnce" ]

dnsNameservers:
- 173.245.58.93
- 173.245.59.247

telemetry: ""

p2pPort: 30333
rpcPort: 9933

extraArgs:
  validator: ""
  bootnode: ""
  common: ""

extraBootnodes: []

local: false

nodeRestart:
  enabled: false
  schedule: "0 4,12,20 * * *"

sessionInjection:
  enabled: true

unsafeEndpointAccess: true
